const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const test = require('node:test')
const init = require('../init')
const { add, diff, manifest } = require('../registry')
const doctor = require('../doctor')

test('init scaffolds a Next.js app with base UI', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'bento-scaffold-'))
  const result = init('.', { cwd, skipInstall: true, skipGit: true })
  assert.equal(result.action, 'ready')
  assert.equal(fs.existsSync(path.join(cwd, 'package.json')), true)
  assert.equal(fs.existsSync(path.join(cwd, 'app/page.tsx')), true)
  assert.equal(fs.existsSync(path.join(cwd, 'app/layout.tsx')), true)
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/theme.css')), true)
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/views/ListView.tsx')), true)
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/primitives/Button.tsx')), true)
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/views/DashboardShell.tsx')), true)
  const packageJson = JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf8'))
  assert.equal(packageJson.dependencies['bento-kit'].startsWith('^0.1.0-preview.'), true)
  assert.equal(packageJson.dependencies.next, '16.1.6')
  assert.equal(fs.readFileSync(path.join(cwd, 'components/bento/theme.css'), 'utf8').startsWith('@import "bento-kit/theme.css";'), true)
  assert.match(fs.readFileSync(path.join(cwd, 'app/page.tsx'), 'utf8'), /ListHost/)
  assert.equal(doctor({ cwd }).ok, true)
  assert.deepEqual(result.registryItems, ['button', 'form', 'dashboard-shell', 'list'])
})

test('init --local points bento-kit at this checkout', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'bento-local-'))
  init('.', { cwd, local: true, skipInstall: true, skipGit: true })
  const spec = JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'), 'utf8')).dependencies['bento-kit']
  assert.equal(spec.startsWith('file:'), true)
  assert.equal(fs.existsSync(path.join(spec.slice('file:'.length), 'package.json')), true)
})

test('init and add are repeatable and protect local changes', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'bento-cli-'))
  fs.writeFileSync(path.join(cwd, 'package.json'), '{"dependencies":{"next":"16.1.6"}}\n')
  init('.', { cwd, skipInstall: true, skipGit: true })
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/theme.css')), true)
  const first = add('list', { cwd })
  assert.equal(first.operations[0].action, 'unchanged')
  assert.equal(JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'))).dependencies['bento-kit'], '^0.1.0-preview.1')
  const second = add('list', { cwd })
  assert.equal(second.operations[0].action, 'unchanged')
  const target = second.operations[0].target
  fs.appendFileSync(target, '\n// local change\n')
  assert.throws(() => add('list', { cwd }), /Local changes detected/)
  assert.equal(add('list', { cwd, dryRun: true }).operations[0].action, 'conflict')
  assert.equal(diff('list', { cwd })[0].action, 'conflict')
  assert.equal(doctor({ cwd }).ok, true)
  assert.ok(manifest.items.some((item) => item.name === 'list'))
})

test('init links the default theme and documentation source is Registry-delivered', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'bento-docs-'))
  fs.writeFileSync(path.join(cwd, 'package.json'), '{"dependencies":{"next":"16.1.6","bento-kit":"^0.1.0-preview.1"}}\n')
  init('.', { cwd, skipInstall: true, skipGit: true })
  assert.equal(fs.readFileSync(path.join(cwd, 'components/bento/theme.css'), 'utf8').startsWith('@import "bento-kit/theme.css";'), true)
  const result = add('documentation', { cwd })
  assert.equal(result.operations[0].action, 'create')
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/views/Documentation.tsx')), true)
})

test('button source exposes functional state without appearance variants', () => {
  const item = manifest.items.find((candidate) => candidate.name === 'button')
  const source = fs.readFileSync(path.join(__dirname, '../../../../registry/button/Button.tsx'), 'utf8')
  assert.deepEqual(item.dependencies, { '@radix-ui/react-slot': '^1.2.4' })
  assert.match(source, /loading\?: boolean/)
  assert.match(source, /aria-busy/)
  assert.doesNotMatch(source, /variant\?:|size\?:|class-variance-authority/)
})
