const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const test = require('node:test')
const init = require('../init')
const { add, diff, manifest } = require('../registry')
const doctor = require('../doctor')

test('init and add are repeatable and protect local changes', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'bento-cli-'))
  fs.writeFileSync(path.join(cwd, 'package.json'), '{"dependencies":{"next":"16.1.6"}}\n')
  init('.', { cwd })
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/theme.css')), true)
  const first = add('list', { cwd })
  assert.equal(first.operations[0].action, 'create')
  assert.equal(JSON.parse(fs.readFileSync(path.join(cwd, 'package.json'))).dependencies['bento-ui'], '^0.1.0-preview.0')
  const second = add('list', { cwd })
  assert.equal(second.operations[0].action, 'unchanged')
  const target = second.operations[0].target
  fs.appendFileSync(target, '\n// local change\n')
  assert.throws(() => add('list', { cwd }), /Local changes detected/)
  assert.equal(add('list', { cwd, dryRun: true }).operations[0].action, 'conflict')
  assert.equal(diff('list', { cwd })[0].action, 'conflict')
  assert.equal(doctor({ cwd }).ok, true)
  assert.ok(manifest.items.some((item) => item.name === 'list'))
})

test('init links the default theme and documentation source is Registry-delivered', () => {
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'bento-docs-'))
  fs.writeFileSync(path.join(cwd, 'package.json'), '{"dependencies":{"next":"16.1.6","bento-ui":"^0.1.0-preview.0"}}\n')
  init('.', { cwd })
  assert.equal(fs.readFileSync(path.join(cwd, 'components/bento/theme.css'), 'utf8').startsWith('@import "bento-ui/theme.css";'), true)
  const result = add('documentation', { cwd })
  assert.equal(result.operations[0].action, 'create')
  assert.equal(fs.existsSync(path.join(cwd, 'components/bento/views/Documentation.tsx')), true)
})

test('button source exposes functional state without appearance variants', () => {
  const item = manifest.items.find((candidate) => candidate.name === 'button')
  const source = fs.readFileSync(path.join(__dirname, '../../registry/button/Button.tsx'), 'utf8')
  assert.deepEqual(item.dependencies, { '@radix-ui/react-slot': '^1.2.4' })
  assert.match(source, /loading\?: boolean/)
  assert.match(source, /aria-busy/)
  assert.doesNotMatch(source, /variant\?:|size\?:|class-variance-authority/)
})
